### ISSUE TITLE
Bufeature: 变量名分词

### ISSUE THREAD

**Issue by ApolloZhu** [Lakr233/myyearwithgit#3]
enumerateSubstrings byWords 不能处理像 `camelCase` 这样的变量名。如果需要进一步分词的话（需要吗？），可以考虑使用 https://stackoverflow.com/a/62527131 一类的

**Comment by Co2333** [comment]
这个明年做吧 确实不是很好 中文也做不了 今年就先 lockdown 了

我们这里还有一大份需求文档 2333 🤣 明年做的那种

嘛你要是提pr我会合上的233
