### ISSUE TITLE
递归查找==套娃

### ISSUE THREAD

**Issue by Innei** [Lakr233/myyearwithgit#4]
建议默认忽略 node_modules 的查找

<img width="742" alt="Screen Shot 2021-12-10 at 1 22 48 PM" src="https://user-images.githubusercontent.com/41265413/145521760-ac274b7d-c6c1-4510-9881-bf248345fa6d.png">

**Comment by Innei** [comment]
已经是个死循环了，cpu 停不下来。

**Comment by Co2333** [comment]
这个是针对子仓库设计的 忽略node modules可以作为一个option 明年写

**Comment by Innei** [comment]
因为 pnpm 这类包管理器有软连接，即便是一层子仓库也可能会无线套娃。

**Comment by Co2333** [comment]
啊这。。。。。。。。 明年修

**Comment by Co2333** [comment]
怎么说呢 其实并不会完全死循环 我上了个限制 最多搜索50层

**Comment by nekomeowww** [comment]
> 怎么说呢 其实并不会完全死循环 我上了个限制 最多搜索50层

但是实际的使用体验不是很好？这段时间就只能干等着了

**Comment by Co2333** [comment]
> > 怎么说呢 其实并不会完全死循环 我上了个限制 最多搜索50层
> 
> 但是实际的使用体验不是很好？这段时间就只能干等着了

明年再说了 今年不打算修了
这仓库你看着像是只有一次提交但实际上已经打了接近30个测试包了
今年玩不动了 🥺 我还要上班 有人说我工作不饱和

**Comment by Lakr233** [comment]
明年复明年 明年何其多 明年修！
